python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id zoom_1
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id zoom_2
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id zoom_3
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id zoom_4
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id zoom_5
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_1
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_2
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_3
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_4
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_5
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_6
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_7
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_8
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_9
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_10
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_11
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_12
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_13
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_14
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id map_15
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id cantook_1
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id cantook_2
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id cantook_3
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id cantook_4
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id cantook_5
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id cantook_6
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id cantook_7
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id cantook_8
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id cantook_9
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id cantook_10
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id cantook_11
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id cantook_12
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_1
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_2
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_3
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_4
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_5
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_6
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_7
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_8
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_9
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_10
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_11
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_12
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_13
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_14
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id bluecoins_15
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_0
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_1
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_2
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_3
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_4
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_5
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_6
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_7
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_8
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_9
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_10
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_11
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_12
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_13
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_14
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_15
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_16
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_17
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_18
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_19
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_20
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_21
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id setting_22
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_1
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_2
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_3
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_4
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_5
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_6
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_7
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_8
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_9
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_10
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_11
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_12
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_13
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_14
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id contacts_15
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_1
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_2
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_3
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_4
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_5
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_6
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_7
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_8
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_9
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_10
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_11
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_12
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_13
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_14
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_15
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_16
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_17
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_18
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_19
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_20
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_21
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_22
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_23
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_24
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_25
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_26
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id clock_27
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id calendar_1
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id calendar_2
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id calendar_3
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id calendar_4
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id calendar_5
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id calendar_6
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id calendar_7
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id calendar_8
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id calendar_9
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id calendar_10
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id calendar_11
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id calendar_12
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id calendar_13
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id calendar_14
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id pimusic_1
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id pimusic_2
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id pimusic_3
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id pimusic_4
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id pimusic_5
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id pimusic_6
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id pimusic_7
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id pimusic_8
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id pimusic_9
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id pimusic_10
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id pimusic_11
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id pimusic_12