python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id gmail_1
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id gmail_2
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id gmail_3
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id gmail_4
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id gmail_5
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id gmail_6
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id gmail_7
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id chrome_1
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id chrome_2
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id chrome_3
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id chrome_4
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id chrome_5
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id chrome_6
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id chrome_7
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id reddit_1
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id reddit_2
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id reddit_3
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id reddit_4
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id reddit_5
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id tiktok_1
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id tiktok_2
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id tiktok_3
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id tiktok_4
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id tiktok_5
python ./../eval.py -n all_cloud_v1_hyper -c ./../configs/example_xml_cloud_hyper.yaml --task_id tiktok_6